### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Mre55** [Lucas-Masaba/TV-shows#21]
https://github.com/Lucas-Masaba/TV-shows/projects/1

- We're a group of two people.

**Comment by D4nielJ** [comment]
## Hello @Mre55 and @Lucas-Masaba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://c.tenor.com/HqR3cqZjITUAAAAM/sheldon-the-big-bang-theory.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
